from src.constants import *
import os, sys


ROOT_DIR = ROOt_DIR_KEY

# feature calcuated dataset
FEATURE_CALCULATED_DATA_PATH = os.path.join(ROOT_DIR, DATA_SOURCE, CALCULATED_FEATURE_DATA, FEATURE_CALCULATED_DATA_CSV)

# Data cleaning dataset
DATA_CLEANING_PATH = os.path.join(ROOT_DIR, DATA_SOURCE, CLEAN_DATA, CLEAN_DATA_CSV)

# feature selection dataset
FEATURE_SELECTION_DATA_PATH = os.path.join(ROOT_DIR, DATA_SOURCE, FEATURE_SELECTION, FEATURE_SELECTION_DATA_CSV)

##save the descriptors
DESCRIPTOR_METHODS_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_FOLDER, SAVE_DESCRIPTOR_FOLDER, DESCRIPTOR_METHODS)
FINGERPRINT_METHODS_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_FOLDER, SAVE_DESCRIPTOR_FOLDER, FINGERPRINT_METHODS)
QM_METHODS_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_FOLDER, SAVE_DESCRIPTOR_FOLDER, QM_METHODS)
DESCRIPTOR_SET_METHODS_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_FOLDER, SAVE_DESCRIPTOR_FOLDER, DESCRIPTOR_SET_METHODS)
FINGERPRINT_TYPES_SUB_CATEGORY_PATH = os.path.join(ROOT_DIR, ARTIFACT_FOLDER, SAVE_DESCRIPTOR_FOLDER, DESCRIPTOR_SET_SUB_CATE_METHODS)

##save the pickle of final model
FINAL_MODEL_PICKLE_PATH = os.path.join(ROOT_DIR, FINAL_MODEL_PICKLE_FOLDER,PICKLE_FILE_NAME)

##save validation dataset
VALIDATION_DATA_PATH = os.path.join(ROOT_DIR, DATA_SOURCE, VALIDATION_DATA_FOLDER,FINAL_VALIDATION_FOLDER, VALIDATION_DATA_CSV)

##save validation dataset
DUPLICATED_CLEAN_VAL_PATH = os.path.join(ROOT_DIR, DATA_SOURCE, VALIDATION_DATA_FOLDER, DUPLICATED_CLEAN_VAL_FOLDER, DUPLICATED_CLEAN_VAL_CSV)
